### PR TITLE
TACACS auth for testing, bigip.conf to JSON

### PR DESCRIPTION
**Pull request by simonkowallik**
- https://github.com/f5-rahm/tacacs_server
- https://github.com/simonkowallik/tmconfjs

### CODE REVIEW

**Comment by DumpySquare** [comment]
for the bigig.conf (tmos) to json, I suggest we utilize corkscrew as that is already complete.  I'd love to bring you up to speed on the project to reduce overlapping work

an example:
https://github.com/f5devcentral/f5-corkscrew/blob/main/tests/artifacts/f5_corkscrew_test.qkview.log.json#L130

**Comment by simonkowallik** [comment]
> for the bigig.conf (tmos) to json, I suggest we utilize corkscrew as that is already complete. I'd love to bring you up to speed on the project to reduce overlapping work
> 
> an example: https://github.com/f5devcentral/f5-corkscrew/blob/main/tests/artifacts/f5_corkscrew_test.qkview.log.json#L130

The focus of corkscrew seems to be more specific (extraction of specific apps) where tmconfjs uses the generic parser supplied with ACC to convert every config to JSON. In addition the goal was to avoid dependencies, which is unreasonable for a project like corkscrew.

I do think corkscrew is a definitive MUST for the awesome-f5 repo though!

**Comment by DumpySquare** [comment]
if your done and everything is working great.  part of the goal of corkscrew, was to focus on apps, and leave behind all the junk.  The outputs are very similar and the dependencies are minimal.    It does have a full json tree of the config, so it can be searched and parsed as needed.  Your tmconfigjs does look more simple and I'd like to see how it handles many of the corner cases I hit.  So, that may be the future.  Maybe we can combine projects in the future to minimize overlap and repo creep.  Nice work by the way.  :)

**Comment by simonkowallik** [comment]
@DumpySquare tmconfjs is merely an interface to the parser of F5 ACC, it does not implement any parsing or even cleanup. It just makes it accessible more easily. So it will deal with special cases or parsing challenges in the same way ACC does at the moment. There are use-cases that require to look at more than the application configuration.

Overlap happens, multiple implementations for similar but not the same objectives happen too. :-)

**Pull request merged**
